### ISSUE TITLE
Issues about fiducial point detection

### ISSUE THREAD

**Issue by zhaodongsun** [godamartonaron/GODA_pyPPG#15]
Hi, thanks for this nice work. When I use pyPPG to detect fiducial points from a PPG signal, there are no fiducial points detected at the end. The figure below shows the issue. The PPG signal is 60Hz. Does the sampling rate cause the issue? How to fix it?

![image](https://github.com/godamartonaron/GODA_pyPPG/assets/33407223/048c89c5-531f-4eb4-833a-5a62bc0ade9f)

**Comment by zhaodongsun** [comment]
Here is another example. 
![image](https://github.com/godamartonaron/GODA_pyPPG/assets/33407223/ee2e22e8-653e-4a08-9084-e0fda489e016)

**Comment by godamartonaron** [comment]
To the onset detection algorithm, a given time window is necessary, therefore you can't see the other fiducial points at the end of the record.

**Comment by zhaodongsun** [comment]
Thanks for your reply!
