### ISSUE TITLE
A bug in PPG_SQI 

### ISSUE THREAD

**Issue by zhaodongsun** [godamartonaron/GODA_pyPPG#16]
Hi, 
there is a bug in the `use_template` function of `ppg_sqi.py` file. Perhaps `else` should be removed.

https://github.com/godamartonaron/GODA_pyPPG/blob/60992a5e287a6c43564207d1908a1e56a5102995/pyPPG/ppg_sqi.py#L174-L177

**Comment by godamartonaron** [comment]
Thank you for your comment! I will check it.

**Comment by godamartonaron** [comment]
updated :)
