### ISSUE TITLE
Usage of correct_IBI in fiducial points detection

### ISSUE THREAD

**Issue by nimrodre** [godamartonaron/GODA_pyPPG#25]
Hi, amazing work with this package.
I find myself debugging your methods in order to better understand the way you implemented fiducial point detection.
When looking at the application of the get_peak_onset method in fiducials.py, during the implementation of the Aboy++ algorithm, you use the correct_IBI method in order to match between the peaks found in all_p4 and px which is understandable and matches the original article by Aboy, but one line further you overwrite your corrected peaks with a scaled version of all_p4. 
Could you please explain if and why there was a reason for this?

These are the lines in question(lines 209-212):
peaks, fn = self.correct_IBI(all_p4, px, np.median(all_hr), fs, up)
peaks = (all_p4/fs*fso).astype(int)
onsets, peaks = self.find_onsets(self.ppg, fso, up, peaks,60/np.median(all_hr)*fs)

I appreciate any help or insight you can give.

**Comment by godamartonaron** [comment]
Hi,
The reason for this:
onsets, peaks = self.find_onsets(self.ppg, fso, up, peaks,60/np.median(all_hr)*fs)

because I also check the peak-onset pairs. In further analysis, I use only complete pulse waves that include both an onset and a systolic peak. I hope this comment is helpful to you.

**Comment by nimrodre** [comment]
Thank you for the quick response, but sadly that is not what's bothered me. The need for peak-onset pairs is understandable, but what I don't understand is these couple of rows:
peaks, fn = self.correct_IBI(all_p4, px, np.median(all_hr), fs, up)
peaks = (all_p4/fs*fso).astype(int)

Why do you first correct the peaks using correct_IBI method and a line further you overwrite them with all_p4?

**Comment by godamartonaron** [comment]
Okay, I understand. The reason is that my correction method using self.find_onsets was more accurate than self.correct_IBI, and I forgot to comment out this line. Due to the previous implementation, I left self.correct_IBI in my code.

**Comment by nimrodre** [comment]
I understand. Thank you for the response!
